AWSTemplateFormatVersion: '2010-09-09'
Description: CloudFormation Tag Provider
Resources:
  LambdaPolicy:
    Type: AWS::IAM::Policy
    Properties:
      PolicyName: CFNCustomTagProviderPolicy
      PolicyDocument:
        Version: '2012-10-17'
        Statement:
          - Effect: Allow
            Sid: ProviderUsed
            Action:
              - tag:GetTagKeys
              - tag:GetTagValues
              - tag:TagResources
              - tag:UntagResources
            Resource:
              - '*'
          - Effect: Allow
            Sid: GeneratedTagActionsFromAPI
            Action:
              - acm:AddTagsToCertificate
              - acm:ListTagsForCertificate
              - acm:RemoveTagsFromCertificate
              - acm:Get*
              - acm-pca:ListTags
              - acm-pca:TagCertificateAuthority
              - acm-pca:Get*
              - alexaforbusiness:ListTags
              - alexaforbusiness:TagResource
              - alexaforbusiness:Get*
              - amplify:ListTagsForResource
              - amplify:TagResource
              - amplify:Get*
              - apigateway:GetTags
              - apigateway:TagResource
              - apigateway:Get*
              - apigatewayv2:GetTags
              - apigatewayv2:TagResource
              - apigatewayv2:Get*
              - appmesh:ListTagsForResource
              - appmesh:TagResource
              - appmesh:Get*
              - appstream:ListTagsForResource
              - appstream:TagResource
              - appstream:Get*
              - appsync:ListTagsForResource
              - appsync:TagResource
              - appsync:Get*
              - athena:ListTagsForResource
              - athena:TagResource
              - athena:Get*
              - autoscaling:CreateOrUpdateTags
              - autoscaling:DeleteTags
              - autoscaling:DescribeTags
              - autoscaling:Get*
              - backup:ListTags
              - backup:TagResource
              - backup:Get*
              - ce:GetTags
              - ce:Get*
              - clouddirectory:ListTagsForResource
              - clouddirectory:TagResource
              - clouddirectory:Get*
              - cloudfront:CreateDistributionWithTags
              - cloudfront:CreateStreamingDistributionWithTags
              - cloudfront:ListTagsForResource
              - cloudfront:TagResource
              - cloudfront:Get*
              - cloudhsm:AddTagsToResource
              - cloudhsm:ListTagsForResource
              - cloudhsm:RemoveTagsFromResource
              - cloudhsm:Get*
              - cloudhsmv2:ListTags
              - cloudhsmv2:TagResource
              - cloudhsmv2:Get*
              - cloudtrail:AddTags
              - cloudtrail:ListTags
              - cloudtrail:RemoveTags
              - cloudtrail:Get*
              - cloudwatch:ListTagsForResource
              - cloudwatch:TagResource
              - cloudwatch:Get*
              - codecommit:ListTagsForResource
              - codecommit:TagResource
              - codecommit:Get*
              - codedeploy:AddTagsToOnPremisesInstances
              - codedeploy:ListTagsForResource
              - codedeploy:RemoveTagsFromOnPremisesInstances
              - codedeploy:TagResource
              - codedeploy:Get*
              - codepipeline:ListTagsForResource
              - codepipeline:TagResource
              - codepipeline:Get*
              - codestar:ListTagsForProject
              - codestar:TagProject
              - codestar:Get*
              - cognito-identity:ListTagsForResource
              - cognito-identity:TagResource
              - cognito-identity:Get*
              - cognito-idp:ListTagsForResource
              - cognito-idp:TagResource
              - cognito-idp:Get*
              - comprehend:ListTagsForResource
              - comprehend:TagResource
              - comprehend:Get*
              - config:ListTagsForResource
              - config:TagResource
              - config:Get*
              - datapipeline:AddTags
              - datapipeline:RemoveTags
              - datapipeline:Get*
              - datasync:ListTagsForResource
              - datasync:TagResource
              - datasync:Get*
              - dax:ListTags
              - dax:TagResource
              - dax:Get*
              - devicefarm:ListTagsForResource
              - devicefarm:TagResource
              - devicefarm:Get*
              - directconnect:DescribeTags
              - directconnect:TagResource
              - directconnect:Get*
              - discovery:CreateTags
              - discovery:DeleteTags
              - discovery:DescribeTags
              - discovery:Get*
              - dms:AddTagsToResource
              - dms:ListTagsForResource
              - dms:RemoveTagsFromResource
              - dms:Get*
              - docdb:AddTagsToResource
              - docdb:ListTagsForResource
              - docdb:RemoveTagsFromResource
              - docdb:Get*
              - ds:AddTagsToResource
              - ds:ListTagsForResource
              - ds:RemoveTagsFromResource
              - ds:Get*
              - dynamodb:ListTagsOfResource
              - dynamodb:TagResource
              - dynamodb:Get*
              - ec2:CreateTags
              - ec2:DeleteTags
              - ec2:DescribeTags
              - ec2:Get*
              - ecr:ListTagsForResource
              - ecr:TagResource
              - ecr:Get*
              - ecs:ListTagsForResource
              - ecs:TagResource
              - ecs:Get*
              - efs:CreateTags
              - efs:DeleteTags
              - efs:DescribeTags
              - efs:Get*
              - elasticache:AddTagsToResource
              - elasticache:ListTagsForResource
              - elasticache:RemoveTagsFromResource
              - elasticache:Get*
              - elasticbeanstalk:ListTagsForResource
              - elasticbeanstalk:UpdateTagsForResource
              - elasticbeanstalk:Get*
              - elb:AddTags
              - elb:DescribeTags
              - elb:RemoveTags
              - elb:Get*
              - elbv2:AddTags
              - elbv2:DescribeTags
              - elbv2:RemoveTags
              - elbv2:Get*
              - emr:AddTags
              - emr:RemoveTags
              - emr:Get*
              - es:AddTags
              - es:ListTags
              - es:RemoveTags
              - es:Get*
              - events:ListTagsForResource
              - events:TagResource
              - events:Get*
              - firehose:ListTagsForDeliveryStream
              - firehose:TagDeliveryStream
              - firehose:Get*
              - fsx:ListTagsForResource
              - fsx:TagResource
              - fsx:Get*
              - glacier:AddTagsToVault
              - glacier:ListTagsForVault
              - glacier:RemoveTagsFromVault
              - glacier:Get*
              - glue:GetTags
              - glue:TagResource
              - glue:Get*
              - greengrass:ListTagsForResource
              - greengrass:TagResource
              - greengrass:Get*
              - groundstation:ListTagsForResource
              - groundstation:TagResource
              - groundstation:Get*
              - guardduty:ListTagsForResource
              - guardduty:TagResource
              - guardduty:Get*
              - iam:ListRoleTags
              - iam:ListUserTags
              - iam:TagRole
              - iam:TagUser
              - iam:Get*
              - inspector:ListTagsForResource
              - inspector:SetTagsForResource
              - inspector:Get*
              - iot:ListTagsForResource
              - iot:TagResource
              - iot:Get*
              - iot1click-devices:ListTagsForResource
              - iot1click-devices:TagResource
              - iot1click-devices:Get*
              - iot1click-projects:ListTagsForResource
              - iot1click-projects:TagResource
              - iot1click-projects:Get*
              - iotanalytics:ListTagsForResource
              - iotanalytics:TagResource
              - iotanalytics:Get*
              - iotevents:ListTagsForResource
              - iotevents:TagResource
              - iotevents:Get*
              - iotthingsgraph:ListTagsForResource
              - iotthingsgraph:TagResource
              - iotthingsgraph:Get*
              - kafka:ListTagsForResource
              - kafka:TagResource
              - kafka:Get*
              - kinesis:AddTagsToStream
              - kinesis:ListTagsForStream
              - kinesis:RemoveTagsFromStream
              - kinesis:Get*
              - kinesisanalytics:ListTagsForResource
              - kinesisanalytics:TagResource
              - kinesisanalytics:Get*
              - kinesisanalyticsv2:ListTagsForResource
              - kinesisanalyticsv2:TagResource
              - kinesisanalyticsv2:Get*
              - kinesisvideo:ListTagsForStream
              - kinesisvideo:TagStream
              - kinesisvideo:Get*
              - kms:ListResourceTags
              - kms:TagResource
              - kms:Get*
              - lambda:ListTags
              - lambda:TagResource
              - lambda:Get*
              - license-manager:ListTagsForResource
              - license-manager:TagResource
              - license-manager:Get*
              - lightsail:TagResource
              - lightsail:Get*
              - logs:ListTagsLogGroup
              - logs:TagLogGroup
              - logs:Get*
              - machinelearning:AddTags
              - machinelearning:DeleteTags
              - machinelearning:DescribeTags
              - machinelearning:Get*
              - mediaconnect:ListTagsForResource
              - mediaconnect:TagResource
              - mediaconnect:Get*
              - mediaconvert:ListTagsForResource
              - mediaconvert:TagResource
              - mediaconvert:Get*
              - medialive:CreateTags
              - medialive:DeleteTags
              - medialive:ListTagsForResource
              - medialive:Get*
              - mediapackage:ListTagsForResource
              - mediapackage:TagResource
              - mediapackage:Get*
              - mediastore:ListTagsForResource
              - mediastore:TagResource
              - mediastore:Get*
              - mediatailor:ListTagsForResource
              - mediatailor:TagResource
              - mediatailor:Get*
              - mq:CreateTags
              - mq:DeleteTags
              - mq:ListTags
              - mq:Get*
              - neptune:AddTagsToResource
              - neptune:ListTagsForResource
              - neptune:RemoveTagsFromResource
              - neptune:Get*
              - opsworks:ListTags
              - opsworks:TagResource
              - opsworks:Get*
              - organizations:ListTagsForResource
              - organizations:TagResource
              - organizations:Get*
              - pinpoint:ListTagsForResource
              - pinpoint:TagResource
              - pinpoint:Get*
              - pinpoint-email:ListTagsForResource
              - pinpoint-email:TagResource
              - pinpoint-email:Get*
              - ram:TagResource
              - ram:Get*
              - rds:AddTagsToResource
              - rds:ListTagsForResource
              - rds:RemoveTagsFromResource
              - rds:Get*
              - redshift:CreateTags
              - redshift:DeleteTags
              - redshift:DescribeTags
              - redshift:Get*
              - resource-groups:GetTags
              - resource-groups:Tag
              - resource-groups:Get*
              - resourcegroupstaggingapi:GetTagKeys
              - resourcegroupstaggingapi:GetTagValues
              - resourcegroupstaggingapi:TagResources
              - resourcegroupstaggingapi:Get*
              - robomaker:ListTagsForResource
              - robomaker:TagResource
              - robomaker:Get*
              - route53:ChangeTagsForResource
              - route53:ListTagsForResource
              - route53:ListTagsForResources
              - route53:Get*
              - route53domains:DeleteTagsForDomain
              - route53domains:ListTagsForDomain
              - route53domains:UpdateTagsForDomain
              - route53domains:Get*
              - route53resolver:ListTagsForResource
              - route53resolver:TagResource
              - route53resolver:Get*
              - s3:DeleteBucketTagging
              - s3:DeleteObjectTagging
              - s3:GetBucketTagging
              - s3:GetObjectTagging
              - s3:PutBucketTagging
              - s3:PutObjectTagging
              - s3:Get*
              - sagemaker:AddTags
              - sagemaker:DeleteTags
              - sagemaker:ListTags
              - sagemaker:Get*
              - secretsmanager:TagResource
              - secretsmanager:Get*
              - securityhub:ListTagsForResource
              - securityhub:TagResource
              - securityhub:Get*
              - servicecatalog:AssociateTagOptionWithResource
              - servicecatalog:CreateTagOption
              - servicecatalog:DeleteTagOption
              - servicecatalog:DescribeTagOption
              - servicecatalog:DisassociateTagOptionFromResource
              - servicecatalog:ListResourcesForTagOption
              - servicecatalog:ListTagOptions
              - servicecatalog:UpdateTagOption
              - servicecatalog:Get*
              - sns:ListTagsForResource
              - sns:TagResource
              - sns:Get*
              - sqs:ListQueueTags
              - sqs:TagQueue
              - sqs:Get*
              - ssm:AddTagsToResource
              - ssm:ListTagsForResource
              - ssm:RemoveTagsFromResource
              - ssm:Get*
              - stepfunctions:ListTagsForResource
              - stepfunctions:TagResource
              - stepfunctions:Get*
              - storagegateway:AddTagsToResource
              - storagegateway:ListTagsForResource
              - storagegateway:RemoveTagsFromResource
              - storagegateway:Get*
              - swf:ListTagsForResource
              - swf:TagResource
              - swf:Get*
              - transfer:ListTagsForResource
              - transfer:TagResource
              - transfer:Get*
              - waf:ListTagsForResource
              - waf:TagResource
              - waf:Get*
              - waf-regional:ListTagsForResource
              - waf-regional:TagResource
              - waf-regional:Get*
              - workspaces:CreateTags
              - workspaces:DeleteTags
              - workspaces:DescribeTags
              - workspaces:Get*
            Resource:
              - '*'
      Roles:
        - !Ref 'LambdaRole'
  LambdaRole:
    Type: AWS::IAM::Role
    Properties:
      ManagedPolicyArns:
        - arn:aws:iam::aws:policy/service-role/AWSLambdaBasicExecutionRole
      AssumeRolePolicyDocument:
        Version: '2012-10-17'
        Statement:
          - Action:
              - sts:AssumeRole
            Effect: Allow
            Principal:
              Service:
                - lambda.amazonaws.com
  CFNTagProvider:
    Type: AWS::Lambda::Function
    DependsOn:
      - LambdaPolicy
    Properties:
      Description: CloudFormation Tag Provider
      PackageType: Image
      Code:
        ImageUri: 463637877380.dkr.ecr.eu-central-1.amazonaws.com/xebia/cfn-tag-provider:1.0.0
      FunctionName: cfn-tag-provider
      Timeout: 600
      MemorySize: 128
      Role: !GetAtt 'LambdaRole.Arn'
